### PR TITLE
Add check for `properties` in GeoJSON objects

### LINKED ISSUE #622: addGeoJSON() fails to render valid geometries
Hi,

it seems that geoJSON geometry primitives such as `"Point"` or  `"Polygon"` are not displayed by `addGeoJSON()`. I would expect them to be valid input as according to the [specification](https://tools.ietf.org/html/rfc7946#section-3) and to `geojsonlint::geojson_validate()` they conform to the standard.

Cheers,
Andrzej

``` r
library(leaflet)
library(jsonlite)
library(geojsonlint)

polygon = list(
  type = "Polygon",
  coordinates = list(
    list(
      c(8.330469, 48.261570),
      c(8.339052, 48.261570),
      c(8.339052, 48.258227),
      c(8.330469, 48.258227),
      c(8.330469, 48.261570)
    )
  )
)

geojson_validate(toJSON(polygon, auto_unbox = TRUE))
#> [1] TRUE

leaflet() %>%
  addTiles() %>%
  addGeoJSON(polygon, color="#F00") %>%
  setView(lng = 8.330469, lat = 48.26157, zoom = 15)
```

``` r

feature <- list(
  type = "Feature",
  properties = "",
  geometry = polygon
)

leaflet() %>%
  addTiles() %>%
  addGeoJSON(feature, color="#F00") %>%
  setView(lng = 8.330469, lat = 48.26157, zoom = 15)
```

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by aoles**
Fixes #622

### CODE REVIEW

**Comment by aoles** [comment]
Hi @schloerke,
looking forward to your feedback on this fix.

Cheers,
Andrzej

**Comment by jcheng5** [comment]
Looks great! @schloerke can we add a visual test?

**Comment by schloerke** [comment]
@jcheng5 Yes. I can add a manual test script.

We can have it run through viztest if we add it as an example.  Any
preference?

**Comment by jcheng5** [comment]
I meant viztest, yeah. Oh, viztest only runs on actual user-facing examples? Could we .Rbuildignore it or something? Or at least prefix the filename with "test" or something?

**Pull request merged**
