### PR TITLE
Upgrade to Leaflet v1.x

### PR DESCRIPTION
**Pull request by jcheng5**
(Note: @timelyportfolio actually did all the heavy lifting for this PR, I just created the PR itself)

Remaining work items. I would much appreciate any help with these.

- [x] Merge recent changes from `master` into `v1.x`
- [x] Upgrade from Leaflet 1.0.3 to 1.2.0
- [x] Update plugins
- [x] Go through the various option defaults in Leaflet 1.x docs, and make sure they match our `xxxOptions` functions and the default values for `addXXX` functions. (A difference in `zIndex` defaults broke rasters)
- [ ] Update package version, NEWS
- [ ] Final round of testing

@bhaskarvk can you also make sure that your `leaflet.extras` don't have any `zIndex = NULL` either?

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@jcheng5 thanks so much for putting this together. I am excited to get Leaflet (R) > 1.0, since the cadence for Leaflet (JS) is so much quicker now.  I'll test and help in any way I can.  Let me know if you want me to tackle anything specifically.

**Comment by bhaskarvk** [comment]
For leaflet.extras I will need to go thru each and every plugin and make sure it's up to date and works with 1.x. So I need some time. My suggestion is to keep this Github only for now, until I make leaflet.extras ready an do a simultaneous release in say 2 or 3 weeks from now.
How does that sound ?

**Comment by bhaskarvk** [comment]
For leaflet.extras I will need to go thru each and every plugin and make sure it's up to date and works with 1.x. So I need some time. My suggestion is to keep this Github only for now, until I make leaflet.extras ready an do a simultaneous release in say 2 or 3 weeks from now.
How does that sound ?

**Comment by bhaskarvk** [comment]
@jcheng5 One more thing, it's been some while after @timelyportfolio updated the plugins and now. So it might be worth the efforts to update them one more time and also update leaflet to 1.2.0 instead of 1.0.3

**Comment by jcheng5** [comment]
I've merged from master, and updated to Leaflet 1.2.0. @timelyportfolio would you have time to upgrade the plugins to their latest versions?

**Comment by timelyportfolio** [comment]
I will start by assembling a checklist of all the plugins we use.  I think I have one somewhere and hope to start chipping away at the list.  Are we talking about both `leaflet` and `leaflet-extras`?

**Comment by bhaskarvk** [comment]
@timelyportfolio just leaflet, I'll deal with the leaflet.extras pkg.

**Comment by bhaskarvk** [comment]
Oh BTW,
leaflet-awesome-markers' original author had long abandoned the project, so I forked it and updated it with some good PRs that were pending on the original repo
https://github.com/bhaskarvk/Leaflet.awesome-markers/commits/2.0/develop
And used this in our `leaflet` package.

I even submitted a PR to the original author of the plugin but he's MIA. Someone else has taken stewardship of the project and made some changes recently and has a PR pending that is essentially my commits copied over.

https://github.com/sigma-geosistemas/Leaflet.awesome-markers/pull/8

So for awesome-markers I have 2 suggestions.
a) Keep it as it is (i.e. copies from my fork) and just make sure it works correctly under leaflet 1.2.0. If something is not working and needs fixing, fork my repo and fix it and use it.
b) fork the /sigma-geosistemas/Leaflet.awesome-markers repo, merge that pending PR8 and also make sure it works for 1.2.0

either way Don't use the original repo.

2) I had also forked Leaflet.Label and merged some pending PRs https://github.com/bhaskarvk/Leaflet.label/commits/master and used that in our package.

Unfortunately this is going to be a bit tricky because this plugin exists no more and Leaflet.Label has become Leaflet.Tooltip in the original `leafletjs`. So it might not be possible to support the new additions that I had made in Leaflet.Label in the next iteration of our package, which I am sure will annoy @jcheng5 :).
For now at least compare my changes to Leaflet.Label and see if the L.Tooltip supports them, and if not  remove those options from the `labelOptions` function. Or if you don't want to break API compatibility deprecate them and make then noop (Issue a warning saying they aren't supported or something).

**Comment by timelyportfolio** [comment]
@jcheng5 @bhaskarvk not sure how best to track the plugin updates.  #458 updates markercluster, and everything seems to work except for `freezeAtZoom`.

**Comment by bhaskarvk** [comment]
@timelyportfolio If you fix the freeze support in #458 I will merge it w/ v1.0 branch.

**Comment by timelyportfolio** [comment]
freeze support fixed in #458.

**Comment by bhaskarvk** [comment]
Almost ready https://github.com/bhaskarvk/leaflet/tree/upgrade/leaflet-v1.x,
I've merged #453, #458, upgraded some more plugins, verified all examples.
Some minor issues to be ironed out, once I do that I'll give you a PR.

**Comment by bhaskarvk** [comment]
Superseded by #476, but keeping open for tracking purposes.

**Pull request merged**
