### PR TITLE
[WIP] Add support for sf

### PR DESCRIPTION
**Pull request by hadley**
Work in progress:

* split up the extraction methods into separate files
* added tests for existing sp behaviour 
* refactored `resolveFormula` to use new `metaData()` generic
* Added sf methods

Includes #348

### CODE REVIEW

**Comment by jcheng5** [comment]
Do you mind just adding the relevant sf classes to the documentation for the leaflet() command, that lists off the types of data that are supported? And NEWS. Other than that, 💯

**Comment by jcheng5** [comment]
(So, 98, I guess.)

**Comment by hadley** [comment]
Done!

**Comment by mdsumner** [comment]
I didn't notice this PR when I commented here: 

https://github.com/rstudio/leaflet/issues/314#issuecomment-270810369

There's no problem to support MULTIPOLYGONs in leaflet now by downgrading them to flat lists of all the rings, it's just that to round-trip them there'll need to be an analysis done to determine hole-ownership, and add the extra structure. I think that's relatively easy now.  I'll add a PR, and a reasonably complicated example.

**Comment by timelyportfolio** [comment]
Are there any examples with `sf` directly in a `leaflet` pipeline?

**Comment by mdsumner** [comment]
There's this: https://github.com/rstudio/leaflet/pull/354

Maybe you can help me, I walked right into the fire and I'm not having much luck hacking at .js. :|

**Comment by timelyportfolio** [comment]
I am trying the new functionality with `LINESTRING` and getting an error.  Most likely, this is a result of my ignorance, but

### reproducible example

```
library(sf)
library(leaflet)

# make a line as shown in sf help
pts = matrix(1:10, , 2)
(ls1 = st_linestring(pts))

leaflet(ls1) %>% addPolygons()
```

### error

```
Error in structure(as.data.frame(x), names = c("lng", "lat")) : 
  'names' attribute [2] must be the same length as the vector [1]
```

### likely source of error

I believe the source of the error is in `leaflet:::sf_coords`.

```
leaflet:::sf_coords(ls1)
```

gives me

```
Error in as.data.frame.default(x) : 
  cannot coerce class "c("XY", "LINESTRING", "sfg")" to a data.frame
```

**Comment by hadley** [comment]
@timelyportfolio please open a new issue

**Comment by timelyportfolio** [comment]
#355

**Pull request merged**
