### PR TITLE
Add WKT2 CRS representation to example data

### PR DESCRIPTION
**Pull request by jcheng5**
I received an email from Roger Bivand via CRAN:

> Dear maintainer,
> 
> Your package leaflet stores data objects using classes defined
> in the sp package or inheriting from those classes. From sp 1.4-* and
> rgdal 1.5-*, CRS objects are now expected to have a comment containing
> an WKT2 CRS representation - see:
> 
> https://www.r-spatial.org/r/2020/03/17/wkt.html
> 
> A section at the foot of
> 
> https://rgdal.r-forge.r-project.org/articles/CRS_projections_transformations.html#rebuilding-crs-objects
> 
> describes possible steps for updating CRS objects; earlier sections cover
> background issues. Working around sp objects with stale CRS is already
> causing difficulties, so your cooperation in upgrading will be helpful.An attempt has been made to rebuild data objects using sp::rebuild_CRS(),
> and output (re-stored as version 2) may be found on my server at:
> 
> http://spatial.nhh.no/R/rebuilt_sp_objects/
> 
> The functions used are from the development version of rgdal, 1.5-17,
> rev >= 1053, use:
> 
> install.packages("rgdal", repos="http://R-Forge.R-project.org")
> 
> and:
> 
> remotes::install_github("rsbivand/sp")
> 
> should you wish to make changes. Please check carefully that these objects
> are as you would expect. Note that the rebuilt CRS object contains
> a revised version of the input Proj4 string as well as the WKT2 string,
> and may be used with both older and newer versions of sp. Objects
> inheriting from sp classes but with NA CRS are not modified.
> 

## Minimal reproducible example

```r
library(leaflet)
comment(atlStorms2005@proj4string)
comment(breweries91@proj4string)
comment(gadmCHE@proj4string)
```

I can confirm that with the new .rda files provided by Roger, these calls return WKT2 strings, while the old copies do not. I also tried using these objects with leaflet and everything works fine.

PR task list:
- [x] Update NEWS
- [ ] Add tests (where appropriate)
  - R code tests: `tests/testthat/`
  - Visual tests: `R/zzz_viztest.R`
- [x] Update documentation with `devtools::document()`

### CODE REVIEW

**Comment by jcheng5** [comment]
Something is wrong with the data, our unit tests convert them from sp to sf and it's throwing errors. I have an email out to Roger asking for guidance.

**Comment by jcheng5** [comment]
Tests are warning, e.g.:

```
test-normalize-2.R:24: warning: normalize
sf layer has inconsistent datum (+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs ).
Need '+proj=longlat +datum=WGS84'
```

Relates to #505, https://github.com/r-spatial/mapview/issues/72. In #505, I promised to get back to the question of automatically transforming sp/sf input after the next CRAN release, but never did. This could be the right time to do it.

**Comment by tim-salabim** [comment]
@jcheng5 what's your take here? Should leaflet do on-the-fly projection or not? It's of course convenient for the user, but somewhat questionable from an educational point of view (from my experience as a geodata scientist).

**Comment by jcheng5** [comment]
This seems to work fine now, I think the `sf` update fixed the warnings.

**Pull request merged**
