### PR TITLE
Update proj4js

### PR DESCRIPTION
**Pull request by pvictor**
Fixes https://github.com/rstudio/leaflet/issues/705

Hello,

I've updated proj4.js library to 2.6.2, removed old files (proj4.js and proj4-compressed.js).

Source for new file: https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.6.2/proj4.min.js

Now leaflet support more projections : 

```r
# DONT WORK WITH CURRENT CRAN VERSION (JavaScript error)
library(leaflet)
world <- rnaturalearth::ne_countries(returnclass = "sf")
leaflet(
  data = world,
  options = leafletOptions(
    crs = leafletCRS(
      crsClass = "L.Proj.CRS",
      code = "ESRI:54030",
      proj4def = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs",
      resolutions = c(65536, 32768, 16384, 8192, 4096, 2048)
    )
  )
) %>% 
  addPolygons(
    weight = 1,
    color = "#FFF",
    opacity = 1,
    fillColor = "blue",
    fillOpacity = 1
  )
```
Result: 
image

Victor

### CODE REVIEW

**Comment by pvictor** [comment]
proj4.js version number don't appear in the htmlwidgets yml since it's in he same block than proj4leaflet, maybe it could be good to separate them ?

PS : I think version number for proj4leaflet is 1.0.2 according to this commit: https://github.com/rstudio/leaflet/commit/c60a979bfaa3af293a32f51c12db7374563a1fbb

**Comment by jcheng5** [comment]
Thanks for the contribution, @pvictor! I do think separating them would make sense; please ensure that the proj4.js entry is inserted _above_ the proj4leaflet entry (I'm assuming they have to be loaded in that order).

**Comment by jcheng5** [comment]
Verified the proj4.min.js is the same as from that link:

```
JMC15-2017:Downloads jcheng$ wget --quiet https://raw.githubusercontent.com/rstudio/leaflet/5d615e46d2c78876c61a2afa5a25488d4147d878/inst/htmlwidgets/plugins/Proj4Leaflet/proj4.min.js
JMC15-2017:Downloads jcheng$ wget --quiet https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.6.2/proj4.min.js
JMC15-2017:Downloads jcheng$ shasum proj4.min.js proj4.min.js.1
4f060c5cc25f6860aab19489d7b03de90fd0c198  proj4.min.js
4f060c5cc25f6860aab19489d7b03de90fd0c198  proj4.min.js.1
```

(Not that I don't trust you @pvictor, just due diligence! :wink:)

**Comment by pvictor** [comment]
Thanks @jcheng5 ! No worries for checking files (I learned something there).

I put proj4 in a new block in the yaml files, which now looks like:

```yaml
  - name: proj4
    version: 2.6.2
    src: "htmlwidgets/plugins/Proj4Leaflet"
    script: proj4.min.js
  - name: Proj4Leaflet
    version: 1.0.1
    src: "htmlwidgets/plugins/Proj4Leaflet"
    script: proj4leaflet.js
```

**Review by jcheng5 — APPROVED** [review]

**Comment by jcheng5** [comment]
Failing CI is unrelated, will fix on master

**Comment by jcheng5** [comment]
Thank you @pvictor!

**Pull request merged**
