### PR TITLE
viztest for #625

### PR DESCRIPTION
**Pull request by schloerke**
PR task list:
- [X] Add tests (if appropriate)
- [X] Update documentation with `devtools::document()`
- [x] Add `@keyword internal`
- [x] remove `library_`

Originally from #622

### CODE REVIEW

**Comment by schloerke** [comment]
Could not validate that it works due to https://github.com/appelmar/gdalcubes_R/issues/11

**Comment by schloerke** [comment]
Diff produced. (expected)

image

**Comment by jcheng5** [comment]
Add `@keyword internal`?

**Comment by jcheng5** [comment]
And remove `library_` pls

**Pull request merged**
