### PR TITLE
fix relative protocol clientside for tile urls

### PR DESCRIPTION
**Pull request by schloerke**
Even with the fix, this error still exists on linux in RStudio with
```r
#now works
leaflet() %>% addTiles()

#still does not work
leaflet() %>% addProviderTiles("CartoDB.Positron")
```

In the inspector...
```
Protocol "https" is unknown 
```

### CODE REVIEW

**Comment by schloerke** [comment]
# Testing Notes. 

All examples should work within RStudio 1.1.x on linux except for the last one. (fails loading https)

``` r
devtools::install_github("rstudio/leaflet#526")                                                    
#> Using GitHub PAT from envvar GITHUB_PAT
#> Using GitHub PAT from envvar GITHUB_PAT
#> Downloading GitHub repo schloerke/leaflet@urlProtocol
#> from URL https://api.github.com/repos/schloerke/leaflet/zipball/urlProtocol
#> Installing leaflet
#> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
#>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
#>   '/private/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T/RtmprL0PE8/devtools987352a32ffb/schloerke-leaflet-1536cca'  \
#>   --library='/Users/barret/z_R_library' --install-tests
#> 
library(leaflet)                                                                                   
                                                                                                   
# should be a normal world                                                                         
leaflet() %>% addTiles()                                                                           
```



``` r
                                                                                                   
# should contain a map of Ames, IA with red dots / fire icons                                      
leaflet() %>% addTiles() %>% addProviderTiles("OpenFireMap") %>% setView(-93.6, 42.0285, zoom = 15)
```



``` r
                                                                                                   
# should contain a map of the USA with blue heatmap-like lines/dots over highway areas             
leaflet() %>% addTiles() %>% addProviderTiles("SafeCast") %>% setView(-97, 38, zoom = 5)           
```



``` r
                                                                                                   
# should contain a greyscale map of the world. Fails on linux & RStudio combo                      
leaflet() %>% addProviderTiles("CartoDB.Positron")                                                 
```

**Comment by tim-salabim** [comment]
On my linux machine in RStudio viewer:

1. works fine 
2. works fine
3. crashes RStudio completely
4. doesn't show any map

**Comment by jcheng5** [comment]
@tim-salabim The crash for 3 is a little scary. 4 is expected.

The situation is not ideal, but I'm guessing this is the best we'll be able to do. For what it's worth, all of these should work perfectly in [RStudio 1.2](https://dailies.rstudio.com) on all platforms.

**Comment by tim-salabim** [comment]
Is it worth testing with a daily RStudio build? If so, I will do so tonite

**Comment by tim-salabim** [comment]
With RStudio version 1.2.567 all 4 examples work as expected, crashing, no blank viewer panes

**Comment by tim-salabim** [comment]
Yes. No crashing :-)

**Pull request merged**
