### PR TITLE
v2.0.1

### PR DESCRIPTION
**Pull request by schloerke**
- [x] `system("npm run build")`
- [x] `devtools::document()`
- [x] `devtools::install()`
- [x] `source("scripts/docs_update.R")`
- [x] Make sure major shiny examples display properly
  * [x] [Super Zip](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) 
`shiny::runApp("../../shiny-examples/shiny-examples/063-superzip-example")`
  * [x] [Bus Dashboard](https://github.com/rstudio/shiny-examples/tree/master/086-bus-dashboard)
`shiny::runApp("../../shiny-examples/shiny-examples/086-bus-dashboard")`
- [x] double check licenses
- [x] `source("scripts/viztest.R")`
- [x] `devtools::release()`, (don't actually release in the last step)
- [x] `source("scripts/rhub.R")`
- [x] `source("scripts/revdepcheck.R")`
- [x] Merge to master, then execute 
```r
devtools:::upload_cran(".", "../builds/leaflet_2.0.1.tar.gz")
```

### CODE REVIEW

**Comment by schloerke** [comment]
@tim-salabim
Tagging to notify on release progress. 😄

**Comment by tim-salabim** [comment]
Thanks! Looking forward to it!

**Comment by schloerke** [comment]
@tim-salabim Submitted to CRAN! Waiting for approval

**Comment by schloerke** [comment]
on CRAN!

**Pull request merged**
