### PR TITLE
Update the draw plugin, include path.drag and more

### PR DESCRIPTION
**Pull request by byzheng**
- Add a new argument group into addDrawToolbar
- Include path.drag
- Change position of  zoomControl

### CODE REVIEW

**Comment by MatthewSchumwinger** [comment]
Hello @byzheng , 
I'm really looking forward seeing these plug-in functionalities added to the main package. Nice work! 

I have a question about addDrawToolbar(). **How do I extract the coordinates of user created objects from the returned value of addDrawToolbar()?**

I am using the following code in a shiny implementation and --as suggested in the function documentation-- am trying to extract the coordinates using `input$drawnItems_create[[3]]$coordinates`. Clearly, this is not the proper usage.  
```
devtools::install_github("byzheng/leaflet") 
library(shiny)
library(leaflet)

shinyUI(bootstrapPage(
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  leafletOutput("map", width = "100%", height = "100%"),
  absolutePanel(top = 80, right = 10, width = 200,
                actionButton("drawPoints", "Draw polygon")
  )
))

shinyServer(function(input, output, session) {

  output$map <- renderLeaflet({
    addTiles(leaflet())
  })
  
  # User draws polygon
  observeEvent(input$drawPoints, {
    leafletProxy("map") %>% 
      addDrawToolbar()
    print(input$drawnItems_create[[3]]$coordinates) # this returns NULL
  })
})
```
Thank you very much for your assistance. Please let me know if you prefer me to ask this question elsewhere.

Best regards,
Matt Schumwinger

**Comment by jcheng5** [comment]
Hi @byzheng, I'm turning my eyes back to the Leaflet package and have been looking at this great PR. Sorry for the trouble but I will need to ask you to sign a Contributor License Agreement with RStudio. It is necessary for us to accept any non-trivial PR, so that we can change the license in the future if we need to (for example, to a future version of the GPL or to BSD/MIT-style license). Once we have a CLA on file for you, it is applicable to any RStudio project.

Please email me at joe@rstudio.com and I'll send you the form, and if it's acceptable to you, you can sign it and send me back a scan or cellphone pic. Thanks and sorry for the inconvenience!

**Comment by bhaskarvk** [comment]
I have implemented this in https://github.com/bhaskarvk/leaflet.extras. Demo at http://rpubs.com/bhaskarvk/leaflet-draw.

**Comment by bhaskarvk** [comment]
Closing this, draw has been implemented in leaflet.draw

**Pull request closed without merging**
