### PR TITLE
Horizontal legend

### PR DESCRIPTION
**Pull request by theGreatWhiteShark**
Hey,

It would be really awesome to have a better control over the legend of the leaflet widget to enable people to make better customizations. 

I hacked a little bit around and I got a version working fine for the shiny app I'm currently writing. But I'm fairly new to JavaScript programming so it probably won't be perfect.

In the R/legend.R::addLegend function I added a argument "orientation" passed to the widget as a option.

With this additional option I trigger if-statements in the inst/htmlwidgets/leaflet.js to render the legend in different ways.

Since the _linear-gradient_ and _svg_ element arn't nicely to tweak using CSS at all I'm also thinking of adding some additional arguments for changing the width and height of the legend.

### CODE REVIEW

**Comment by theGreatWhiteShark** [comment]
I tweaked the code a bit. Now the ticks and labels are in place regardless of the display size (at least the 4 ones I checked).

Also the height and the width of the legend can now be controlled via the shiny app. (Which is really handy for customizing the view)

In addition there is no overlap of the labels in the horizontal orientation anymore. The (R) code will take the desired number of bins, calculates the width of all labels (via a heuristic) and incrementally decreases the bin number until the labels fit below the color-bar without overlap.

I'm not quite sure if I can add some additional commits to an existing pull request but since no one viewed this one in a month I also don't want to start a second one.

**Comment by bhaskarvk** [comment]
@theGreatWhiteShark I reallly like this PR, but you've directly changed inst/htmlwidgets/leaflet.js which is not the way to go about it.
`inst/htmlwidgets/leaflet.js` is now auto generated and should not be directly edited. You need to change src/javascript/methods.js and then run `grunt build` from the project root.

If you've never set up the grunt part before take a look at this slide
https://bhaskarvk.github.io/leaflet-talk-rstudioconf-2017/RstudioConf2017.html#35. You will need node.js and npm.

**Comment by theGreatWhiteShark** [comment]
Ah, and all of it  even is described in the README. Sorry about that. I was just following this guide http://www.htmlwidgets.org/develop_intro.html :)

I will set up the same stuff using grunt.

**Comment by theGreatWhiteShark** [comment]
Alright, I applied all changes to javascript/src/method.js

**Comment by bhaskarvk** [comment]
May be you forgot to push your changes, I don't see them on this PR.

**Comment by theGreatWhiteShark** [comment]
Sorry. I was pushing to master the whole time. But now everything is in place.

**Comment by tiernanmartin** [comment]
What's the ETA on merging this PR? I'd love to play around with the legend orientation.

**Comment by bhaskarvk** [comment]
@jcheng5 one more PR to consider before new CRAN release.

**Comment by schloerke** [comment]
Hi @theGreatWhiteShark 

Could you ...

"
 2. Ensure that you have signed the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement as appropriate. You can send the signed copy to jj@rstudio.com.
"
Excerpt from [rstudio/httpuv package](https://github.com/rstudio/httpuv/blob/master/CONTRIBUTING.md), which you had no reason to know existed.

Please let me know when you've sent the email.  Thank you for your help!

Best,
Barret

**Comment by theGreatWhiteShark** [comment]
Alright. I just sent the mail

**Comment by schloerke** [comment]
I've merged your commits and the next release branch into branch... https://github.com/schloerke/leaflet/tree/horizontal_legend

Changes:
* lints
* changed to larger character width (my computer displayed 7.78 px vs 4 px)
* attempted to detect the maximum label size.  
* altered how the legend label text was positions as it was not directly underneath the tick mark

Still broken:
* reasonably large text labels (like "10,000") are only producing a single bin when there should be at least two
* bins are not being respected when calculated within `generate_legend(bins)`

Cases that need testing (even if it is `testthat::expect_silent({....})` )
* With pal or with colors and labels
* With data of each type of pal (numeric, quantile, ...)
* With numeric data that spans many magnitudes (so labels are of very different size)

**Comment by theGreatWhiteShark** [comment]
Thanks. It's been a while since I looked into leaflet- and shiny-based stuff. But as soon as I am done with some other projects I'm currently working on, I'll try to help making my first lines of JavaScript code failsafe and usable.

**Comment by laurenmarietta** [comment]
Just found this PR as I was looking for a way to make my legend horizontal. Curious to get an update on what prevented @theGreatWhiteShark's code from being merged in?

**Pull request closed without merging**
