### PR TITLE
update markercluster->v0.1.1, leaflet-measure->2.1.7, leaflet-omnivore->0.3.4

### PR DESCRIPTION
**Pull request by timelyportfolio**
I updated 

- leaflet-markerCluster -  All seems to work except for `freezeAtZoom` using [example](https://github.com/rstudio/leaflet/blob/master/inst/examples/marker-clustering.R#L17-L18)
- leaflet-measure - think all good
- leaflet-omnivore - tried and doesn't seem to work
    ```
    topoData <- readLines("https://d3js.org/us-10m.v1.json") %>% paste(collapse = "\n")
    
    leaflet() %>% setView(lng = -98.583, lat = 39.833, zoom = 3) %>%
      addTiles() %>%
      addTopoJSON(topoData, weight = 1, color = "#444444", fill = FALSE)
    ```

### CODE REVIEW

**Comment by bhaskarvk** [comment]
There were 2 sub plugins of the marker cluster plugin.
https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport To support Layer Group Control + Clustering &
https://github.com/ghybs/Leaflet.MarkerCluster.Freezable To support Freezing.
You probably need to upgrade them both too.

**Comment by timelyportfolio** [comment]
@bhaskarvk, I updated both this morning, and I don't see any API changes, but for some reason, `freezeAtZoom` is not working.  Here is the freeze example from the plugin where it is working with Leaflet 1.0.1

I'll keep trying.

**Comment by timelyportfolio** [comment]
@bhaskarvk, I just figured it out.  freeze and layersupport don't work together.  If I use `markerClusterGroup()` instead of `markerClusterGroup.layerSupport`, then `freezeAtZoom` works correctly.  I will try to debug to submit pull or at a minimum file a detailed issue.

**Comment by timelyportfolio** [comment]
... but (maybe @bhaskarvk can help) I just discovered that the easyButton [example](https://github.com/rstudio/leaflet/blob/master/inst/examples/easyButton.R#L15-L48) freeze works.  This could be that it uses markerCluster directly instead of layersupport.

**Comment by bhaskarvk** [comment]
@timelyportfolio If I have to chose between freeze support or layersupport I would chose layersupport.. The layersupport plugin is crucial for supporting clustering + layers. I think that is more important to have than freezeAtZoom.
Also in 0.7.x the freezeAtZoom + layerSupport was working perfectly fine, so it's probably best to raise an issue w/ these plugin author/s to see why it's not working in 1.2.0.

**Comment by timelyportfolio** [comment]
@bhaskarvk I got a very quick response from the author with a workaround (https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport/issues/13), but I'm not sure we will want to include.  I tend to agree layer support is more important than freezable.

**Comment by bhaskarvk** [comment]
@timelyportfolio Why are you unsure about including the fix ?

**Comment by timelyportfolio** [comment]
@bhaskarvk, I guess we include the fix.  I just did not know if temporary hack/patch would be deemed acceptable in production.  I will let @jcheng5 decide.

**Comment by bhaskarvk** [comment]
I am fine with using a fixed plugin. I have had to do that in past too for some of the plugins in both leaflet and leaflet.extras. @timelyportfolio could you add the fix to this PR and I can test it out.

**Comment by timelyportfolio** [comment]
Thanks @bhaskarvk I hope to get this done by end of the weekend.

**Comment by timelyportfolio** [comment]
@bhaskarvk, I finally got it to work using https://github.com/ghybs/Leaflet.MarkerCluster.Freezable/commit/d3953036bf337e140162dcbab50bc7d35bf2f28e and changing the order of the load/dependencies [commit](https://github.com/rstudio/leaflet/pull/458/commits/d40024c917ec1350a77dda22e84781568ed2176d).  

Please test if you get a chance.

**Comment by timelyportfolio** [comment]
@bhaskarvk, have you had a chance to look at this?  Thanks.

**Comment by bhaskarvk** [comment]
I will look over this over the coming weekend. Promise!

**Comment by bhaskarvk** [comment]
I will review this tonight and merge in the 1.x branch

**Comment by bhaskarvk** [comment]
Almost ready https://github.com/bhaskarvk/leaflet/tree/upgrade/leaflet-v1.x,
I've merged #453, #458, upgraded some more plugins, verified all examples.
Some minor issues to be ironed out, once I do that I'll give you a PR.

**Comment by bhaskarvk** [comment]
I've merged this in my https://github.com/bhaskarvk/leaflet/commits/upgrade/leaflet-v1.x and will be pushed as part of LeafletJS 1.x upgrade.

**Comment by bhaskarvk** [comment]
Superseded by #476, but keeping open for tracking purposes.

**Comment by schloerke** [comment]
This code has been merged into master #492. Closing.  Thank you!!

**Pull request closed without merging**
