### PR TITLE
Add support for scale bar

### PR DESCRIPTION
**Pull request by kent37**
Add support for leaflet.control.scale #198 

Includes `addScaleBar()`, `scaleBarOptions()` and `removeScaleBar()` implementing access to `leaflet.control.scale`.

### CODE REVIEW

**Comment by jcheng5** [comment]
Thanks! I had started on this (https://github.com/rstudio/leaflet/compare/feature/scale) but it looks like you got a little further...

**Comment by kent37** [comment]
You're welcome! Nothing like needing something to motivate one!

**Comment by jcheng5** [comment]
@kent37 Can you email me at joe@rstudio.com? We can't merge pull requests unless the author signs a Contributor License Agreement. This allows us to change the license in the future (for example, from GPL to BSD/MIT) if we want to. If you email me I'll send you a copy of our CLA, which you can review, sign, and email me a scan or cellphone pic.

Thanks and sorry for the inconvenience.

**Comment by jcheng5** [comment]
Note to self: CLA received

**Comment by seantma** [comment]
@jcheng5 Just curious, is addScaleBar() added in version 1.01 or still in the development version? Thanks!

**Pull request merged**
