### PR TITLE
Add topojson support via omnivore plugin

### PR DESCRIPTION
**Pull request by jcheng5**

### CODE REVIEW

**Comment by yihui** [comment]
Do you need a method `methods.addTopoJSON()` in inst/htmlwidgets/leaflet.js accordingly?

**Comment by jcheng5** [comment]
I've included it in a separate file, inst/htmlwidgets/plugins/leaflet-omnivore-plugin.js

I just realized I commented out the mouse handling and never went back and fixed it. Let's leave this open until I have a chance to do that.

**Comment by yihui** [comment]
OK I see.

**Comment by jcheng5** [comment]
Hey @yihui, I think this is ready now.

**Comment by yihui** [comment]
LGTM. Is it worth squashing the commits into one? (since there are some files added and removed) I'm fine with merging it as is.

**Pull request merged**
