### PR TITLE
Fix: replace Stamen/Stadia in vignettes, function documentation, and `inst` examples

### LINKED ISSUE #912: Broken basemaps on {pkgdown} site
Good morning,

Just highlighting there are broken basemaps in the `{pkgdown}` site.

This is almost certainly to do with #883. Interestingly, the basemaps load in an interactive session, but not on the hosted website.

e.g., https://rstudio.github.io/leaflet/articles/basemaps.html:

image

### PR DESCRIPTION
**Pull request by jack-davison**
This fixes #912 and a bit more.

- I've replaced all "Stadia" (formerly "Stamen") tiles in the vignettes with tile providers which should display on the `{pkgdown}` website. Can see the present issue at: https://rstudio.github.io/leaflet/articles/basemaps.html#combining-tile-layers

- I've also gone through and replaced all of the "Stamen" examples in the function docs with alternates. These would not work after the Stamen/Stadia situation described in #883 anyway, so need fixing regardless of the above point!

These fixes only change the providers in examples, and anything directly associated with them (e.g., if the `group` was "Stamen" before it's now "Carto", and in one instance the colour of circles was changed to stand out better on a new basemap).

Re-ran `devtools::document()`.

### CODE REVIEW

**Review by schloerke — APPROVED** [review]

**Comment by schloerke** [comment]
Thank you!

**Comment by gadenbuie** [comment]
@schloerke ICYMI I replied in the issue: https://github.com/rstudio/leaflet/issues/912#issuecomment-2032599178. I'm in favor of cutting down on our usage of Stadia maps but we should keep at least one or two examples and we should go through the stated process of setting up domain-based auth so we can have experience with the process and also monitor how it works.

**Comment by schloerke** [comment]
@gadenbuie Totally did. Thank you!

**Review by gadenbuie — APPROVED** [review]
Thanks @jack-davison! I added one of the Stamen examples back (under "Third-party tiles") along with some instructions on migrating to Stadia.

I also registered an account and added our `rstudio.github.io` domain to the allowlist, so the Stamen tiles should work as expected in our docs.

**Pull request merged**
