### PR TITLE
relative urls for openstreetmap tiles

### PR DESCRIPTION
**Pull request by mhines-usgs**
suggested change for either http or https for openstreetmap requests using relative urls

### CODE REVIEW

**Comment by bhaskarvk** [comment]
+1 for this PR.

**Comment by mhines-usgs** [comment]
Any ETA on merging this? or other suggestions to hurry it along? Thanks :D

**Comment by isuftin** [comment]
👍

**Comment by jcheng5** [comment]
Thanks for the PR! And sorry for the delay.

**Comment by bhaskarvk** [comment]
Actually there is a problem w/ using protocol relative url. If you do

```r
l <- lealfet() %>% addTiles()
htmlwidgets::savewidget(l, 'l.html')
```

And open the file in a browser over the `file://` protocol, the `//` of the tile URL template becomes `file://` and thus no tiles are loaded.

**Comment by mhines-usgs** [comment]
That's a bummer! I didn't realize that was a use case (local file://) 

I can't think of a workaround for that need. Do you have suggestions for avoiding mixed content warnings where this is hardcoded to http and being used on an https website? 

There are other places in the package that have relative URLs, do those not cause issues with file:// access?

This package is pulled in at build currently, my other idea is forking it and pointing at that fork instead of the master repo, if need be.

**Comment by jcheng5** [comment]
Crap, I missed this issue. The fix is to simply use https I think.

**Pull request merged**
