### PR TITLE
Remove NA's from addCirlce's lng and lat arguments as the default.  

### PR DESCRIPTION
**Pull request by hansthompson**
Perhaps na.ignore would be a better method? I address the reason for this pull in issue 71.
https://github.com/rstudio/leaflet/issues/71
Thanks for making such a great piece of software. Sorry if I'm messing with your code flow.

### CODE REVIEW

**Comment by yihui** [comment]
I don't know why you choose to merge into the `feature/better-defaults` branch. You should choose the master branch instead.

I think this NA issue is a general one (not specific to `addCircles()`), so we have to think about other `add*()` functions as well.

**Comment by hansthompson** [comment]
Please forgive me.  I thought it fit under "better defaults" but after I wasn't sure and after a few minutes of thinking about it I just hit the button.

**Comment by hansthompson** [comment]
Should I make a pull request to the master and close this one down?

**Comment by yihui** [comment]
If you want, yes. But as I said, `addCircles()` does not seem to be the only thing that we need to fix. There are several other functions in this package that should consider NAs in lat/lng as well, and it will be nice to fix them all.

There are two possible ways to fix this issue: one is on the R side (exclude NA's from lat/lng), and the other is on the JavaScript side. I do not quite prefer the first way, since it may screw up other arguments such as `layerId`, e.g. the `layerId` vector will not match the lat/lng vectors after you exclude NAs from lat/lng.

@jcheng5 Any thoughts?

**Comment by jcheng5** [comment]
I think it's only `addCircles`, `addMarkers`, and `addCircleMarkers` that are susceptible to NA. If you have, for example, polygon or rectangle data that includes NA points, that feels more like an error to me.

Out of curiosity, what kind of data do you have that you are ending up with NA lat/long values in the first place? Or is it NA radius (which would make more sense to me)?

**Comment by hansthompson** [comment]
I'm doing an analysis for our bus tracking website, http://bus.codeforanchorage.org/. We store requests for real time bus data in gps, addresses, and bus stop ids. We get mostly gps requests which come out of our database a string. The script converts the requests that it can back to gps and then plots it. 

I could remove the NAs but do you think this could be categorized unexpected behaviour? I really like how ggplot handles NAs by putting them as a warning. Would that be a better implementation?

**Comment by jcheng5** [comment]
I ran into this myself last week (real data with missing NA), it was quite annoying and I think you're right that we should warn. How about warning on the R side but actually doing the omitting on the JS side? I think that gives us best of both worlds.

**Comment by masip85** [comment]
Yes,quite problematic issue. Every data after NA from your DF or DT is ommited and you can only see a portion of it. If you have a large dataset maybe the difference isn't noticed.
And rest of layers after NA's layer , doesn't plot anything.

**Comment by bhaskarvk** [comment]
Closing as I'm tracking this under #304

**Pull request closed without merging**
