### PR TITLE
add info about map center input event to doc

### PR DESCRIPTION
**Pull request by michael-chong**

### CODE REVIEW

**Comment by bhaskarvk** [comment]
@jcheng5 Another one.

**Comment by bhaskarvk** [comment]
@jcheng5 Looks like a good documentation update.

**Comment by schloerke** [comment]
Hi Michael,

Could you ...

"
 2. Ensure that you have signed the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement as appropriate. You can send the signed copy to jj@rstudio.com.
"
Excerpt from [rstudio/httpuv package](https://github.com/rstudio/httpuv/blob/master/CONTRIBUTING.md), which you had no reason to know existed.

Please let me know when you've sent the email.  Thank you for your help!

Best,
Barret

**Comment by schloerke** [comment]
This change has been added to the docs.  Closing. Thank you!

**Pull request closed without merging**
