### PR TITLE
Auto show/hide legend using layer control

### PR DESCRIPTION
**Pull request by bhaskarvk**
Auto show/hide legend based on a overlay group. 

A lot of people have asked for this feature, where the legend should auto show/hide based on toggling an overlay group. I've modified the example to show how it works.

### CODE REVIEW

**Comment by jakeander** [comment]
Is this supposed to hide a legend when I toggle the layer control on the right? I ran the function and the example and the legend remains on the map.

**Comment by bhaskarvk** [comment]
Could you upload it on round for me to look at?

**Comment by jakeander** [comment]
All I did was run the R/legend.R script from the files changed tab then I ran the inst/examples/legend.R file. The maps with the circle markers pops up but when I toggle the 'circles' group, the legend on the bottom left remains.

**Comment by tim-salabim** [comment]
It does work for me, both layer and legend are toggled with the layer control. Sweet!! Looking forward to have this in master

**Comment by bhaskarvk** [comment]
@jakeeander you need to properly install the package, not just source the R files. Before running the example do `devtools;:install('rstudio/leaflet')`

**Comment by bhaskarvk** [comment]
Oops sorry you need to install this PR and not the master as this hasn't been merged yet.

**Comment by bhaskarvk** [comment]
@jcheng5 Could you review and merge this if OK ?

**Comment by jakeander** [comment]
I used this PR and it worked. Much appreciated! Great work. This is just supposed to work with the overlayGroups parameter and not the baseGroups parameter correct?

**Comment by bhaskarvk** [comment]
For now overlay groups  only, I figured base groups are for base mala but it's not too hard to add the functionality for base map changes too if required.

**Comment by jakeander** [comment]
That would be a great addition for me. I've made some maps where the baseGroups parameter switches based on different addPolygons set of data. That works well and then an overlayGroups parameter would be set to locations using addCircles or addMarkers.

**Comment by bhaskarvk** [comment]
OK I will add that feature

**Comment by lbeisteiner** [comment]
any update on merging this? I would really appreciate this feature!

**Comment by jcheng5** [comment]
@bhaskarvk Seems like it should respect `showGroup` and `hideGroup` as well. Maybe ControlStore should have the concept of groups added to it, and controls that are added with a group can be linked through LayerManager's group layer's events.

**Comment by bhaskarvk** [comment]
Good point. Unfortunately I have no free time for the foreseeable future to work on this. I think I can get back to this my mid may, but probably not before that.

**Comment by bhaskarvk** [comment]
Actually on second thought, my PR will work correctly with `(show|hide)Group` because it will trigger a overlayGroup add/remove event, and the eventlistener in this PR will kick in and add/remove the legend. I just don't have time right now to verify that.

**Comment by jcheng5** [comment]
It doesn't, I think because the event only fires when the control is used. But we could fire a similar event from the show/hide methods, that'd be a cheap but still sorta general fix.

**Comment by osh-chicago** [comment]
Sorry for the basic question, but would someone please let me know how I can add this update to my version of leaflet?

Thanks!

**Comment by bhaskarvk** [comment]
I should be able to work on this next week.

**Comment by osh-chicago** [comment]
@bhaskarvk Thanks so much!

**Comment by bhaskarvk** [comment]
Working on a new PR based of master. Closing this.

**Comment by osh-chicago** [comment]
Glad to hear!

When do you think this will be ready, please? @bhaskarvk

**Comment by bhaskarvk** [comment]
Hoping to work on this over the weekend.

**Comment by osh-chicago** [comment]
Hi @bhaskarvk - did you get the chance to work on this? Thanks!

**Comment by bhaskarvk** [comment]
New PR #442.
@jakeander Unfortunately supporting baselayer change is not easy. It's not impossible but I am not fully convinced of the use case to add an ugly hack for the use case.

**Pull request closed without merging**
