### PR TITLE
Fix issue 595

### PR DESCRIPTION
**Pull request by martinjhnhadley**
`leaflet` failed to visualise `sf` objects where `st_geometry` contained names (https://github.com/rstudio/leaflet/issues/595)

This PR fixes this issue

```r
library("magrittr")
library("sf")
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
library("leaflet")

download.file(url = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip",
              destfile = "world-shape-files.zip")
unzip("world-shape-files.zip", exdir = "world-shape-files")
unlink("world-shape-files.zip")

world_shapefiles <- read_sf("world-shape-files")
colnames(world_shapefiles) <- make.names(tolower(colnames(world_shapefiles)))

world_shapefiles %>%
  leaflet() %>%
  addPolygons()
```

image

PR task list:
- [x] Update NEWS
- [x] Add tests (if appropriate)
- [x] Update documentation with `devtools::document()`

### CODE REVIEW

**Comment by tim-salabim** [comment]
See https://github.com/r-spatial/sf/issues/909

Sf soon to drop names of geometry column

**Comment by schloerke** [comment]
@jcheng5 should we merge this anyways? or just wait it out until sf releases again

**Comment by tim-salabim** [comment]
heads-up, sf just hit cran

**Comment by schloerke** [comment]
Hi @martinjhnhadley 

Could you ...

"
 2. Ensure that you have signed the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement as appropriate. You can send the signed copy to jj@rstudio.com.
"
Excerpt from [rstudio/httpuv package](https://github.com/rstudio/httpuv/blob/master/CONTRIBUTING.md), which you had no reason to know existed.

Please let me know when you've sent the email.  Thank you for your help!

Best,
Barret

**Comment by martinjhnhadley** [comment]
Hey @schloerke! I've sent the email 😀

**Pull request closed without merging**
