### PR TITLE
Raster image support

### PR DESCRIPTION
**Pull request by jcheng5**
This branch introduces `addRasterImage`, `removeImage`, and `clearImages` functions. These functions can be used to incorporate small-ish RasterLayer objects (from the `raster` package) into maps, by (optionally) projecting them, coloring them, PNG and base64 encoding them, and finally embedding them directly into the widget data.

There's some complexity in the JS file, it turns out that Leaflet's ImageOverlay feature didn't work reliably for me and didn't support nearest-neighbor interpolation.

Incidentally, there's now an `alpha` parameter to the color functions. If `TRUE` then alpha interpolation will be performed and `#RRGGBBAA` strings will be returned.

**Note that this PR introduces a dependency on jcheng5/rasterfaster.** This may change to hadley/scales if he accepts https://github.com/hadley/scales/pull/57, though rasterfaster will come back when we get around to making addRasterTiles work properly.

### CODE REVIEW

**Comment by jcheng5** [comment]
Ack, just realized I am missing some options.

- [ ] Min/max zoom levels
- [ ] detectRetina
- [ ] reuseTiles

Also, note that this feature doesn't work in older IE versions as it relies on canvas.

**Comment by jcheng5** [comment]
Tested on Chrome and Firefox on Linux, and IE10 on Windows 8.

**Comment by jcheng5** [comment]
Fixes #73

**Comment by jcheng5** [comment]
Change rasterfaster dependency to scales

**Comment by jcheng5** [comment]
@yihui I can't remember, did I say I was going to fix something else besides moving from `rasterfaster` dependency to `scales`?

**Comment by yihui** [comment]
I don't remember, either.

**Pull request merged**
